name: glogai-scan
on:
  workflow_dispatch:
  
jobs:
  glog-scan-ghcr:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4.2.1
        with:
            distribution: 'temurin'
            java-version: 23
            architecture: x64
            cache: 'maven'
            
      - name: Build with Maven
        run: mvn --no-transfer-progress package -DskipTests
      
      - name: Checkout glog-action repository
        uses: actions/checkout@v4
        with:
           repository: glogai/glog-action
           token: ${{ secrets.PAT_TOKEN }}
           path: .github/glog-action
           ref: main

      - name: Run GlogAI from private repo
        uses: ./.github/glog-action
        with:
          lang: 'java'
          debug: 'true'
          upload: 'true'
          github-token: ${{ secrets.PAT_TOKEN }}
          glog-token: ${{ secrets.GLOG_TOKEN }}
